In [1]:
import pandas as pd 
import numpy as np 
import random 
import os 
import json 
import matplotlib.pyplot as plt 
import seaborn as sns 
from datetime import datetime, timedelta 
import funcoes

In [2]:
caminho_do_arquivo = '../dados/raw/vendas.csv'
df_original = pd.read_csv(caminho_do_arquivo)

In [3]:
df_original

,id_venda,data_venda,cliente,produto,categoria,regiao,quantidade,preco_unitario
0,1,2024-01-13,Cliente_024,Mouse,Periféricos,Norte,2.0,120.0
1,2,2024-08-04,Cliente_018,Notebook,Computadores,Sul,NaN,3500.0
2,3,DATA INVALIDA,Cliente_026,Mouse,Periféricos,Sul,9.0,120.0
3,4,2024-06-23,Cliente_013,Mouse,Periféricos,Sudeste,7.0,120.0
4,5,2024-11-05,Cliente_030,Tablet,Celulares,Centro-Oeste,6.0,1800.0
...,...,...,...,...,...,...,...,...
145,146,2024-08-09,Cliente_019,Notebook,Computadores,Norte,2.0,3500.0
146,147,2024-12-09,Cliente_028,Teclado,Periféricos,Sudeste,6.0,250.0
147,148,2024-06-08,Cliente_008,Tablet,Celulares,Sudeste,10.0,1800.0
148,149,2024-07-07,Cliente_018,Tablet,Celulares,Norte,9.0,1800.0
149,150,2024-01-14,Cliente_009,Teclado,Periféricos,Nordeste,9.0,250.0

In [4]:
funcoes.analise_dados(df_original)

,Tipos de Dados,Qtd_Não_Nulos,Valores Únicos,Qtd_Nulos,% Nulos,Duplicados
id_venda,int64,150,150,0,0.0%,0
data_venda,object,150,113,0,0.0%,0
cliente,object,150,30,0,0.0%,0
produto,object,150,9,0,0.0%,0
categoria,object,150,3,0,0.0%,0
regiao,object,150,5,0,0.0%,0
quantidade,float64,144,10,6,4.0%,0
preco_unitario,float64,147,6,3,2.0%,0

Para ficar fácil de interpretar, nós dividimos esses indicadores em três grupos: os de Texto, os de Média/Dispersão, e os de Posição (Quartis).
1) O Grupo dos Textos (Variáveis Categóricas): unique (qauntos valores unicos), top (moda) e freq (nºx moda aparece)
2) O Grupo de Posição (Os Quartis) e o 50% (Mediana)
--> Sempre confie mais na Mediana (50%) para entender o comportamento do seu "cliente padrão".
--> O método estatístico mais famoso do mundo para detectar outliers usa exatamente eles. Chama-se Método IQR (Intervalo Interquartil).

In [5]:
funcoes.resumo_estatistico(df_original)

,id_venda,data_venda,cliente,produto,categoria,regiao,quantidade,preco_unitario
count,150.0,150,150,150,150,150,144.0,147.0
unique,-,113,30,9,3,5,-,-
top,-,2024-05-15,Cliente_024,Notebook,Celulares,Sudeste,-,-
freq,-,5,8,27,53,42,-,-
mean,75.5,-,-,-,-,-,5.42,1596.12
std,43.45,-,-,-,-,-,2.71,1178.31
min,1.0,-,-,-,-,-,1.0,120.0
25%,38.25,-,-,-,-,-,3.0,250.0
50%,75.5,-,-,-,-,-,5.0,1800.0
75%,112.75,-,-,-,-,-,8.0,2200.0
max,150.0,-,-,-,-,-,10.0,3500.0

In [ ]:
funcoes.contagem_valores(df_original)

--- RELATÓRIO DE VALORES ÚNICOS E CONTAGENS ---

[ ID_VENDA ] -> 150 valores. (Omitido)

[ DATA_VENDA ]
2024-05-15: 5  |  DATA INVALIDA: 4  |  2024-11-22: 4  |  2024-02-08: 3  |  2024-10-26: 3
2024-11-01: 2  |  2024-07-21: 2  |  2024-05-30: 2  |  2024-09-16: 2  |  2024-07-29: 2
2024-05-05: 2  |  2024-05-08: 2  |  2024-02-25: 2  |  2024-07-23: 2  |  2024-10-22: 2
2024-01-17: 2  |  2024-11-05: 2  |  2024-08-28: 2  |  2024-08-08: 2  |  2024-04-22: 2
2024-12-03: 2  |  2024-03-07: 2  |  2024-03-20: 2  |  2024-06-16: 2  |  2024-07-04: 2
2024-11-27: 2  |  2024-05-27: 2  |  2024-06-08: 2  |  2024-06-30: 1  |  2024-05-16: 1
2024-01-25: 1  |  2024-03-24: 1  |  2024-01-13: 1  |  2024-06-02: 1  |  2024-11-14: 1
2024-01-21: 1  |  2024-05-02: 1  |  2024-10-31: 1  |  2024-09-05: 1  |  2024-05-01: 1
2024-12-15: 1  |  2024-07-16: 1  |  2024-07-05: 1  |  2024-04-17: 1  |  2024-08-04: 1
2024-06-23: 1  |  2024-05-28: 1  |  2024-03-26: 1  |  2024-08-14: 1  |  2024-08-25: 1
2024-11-18: 1  |  2024-04-25: 1  |  2024-03-27: 1  |  2024-12-12: 1  |  2024-12-27: 1
2024-04-30: 1  |  2024-08-06: 1  |  2024-01-10: 1  |  2024-04-12: 1  |  2024-12-24: 1
2024-01-22: 1  |  2024-02-24: 1  |  2024-07-18: 1  |  2024-08-27: 1  |  2024-02-12: 1
2024-11-26: 1  |  2024-06-21: 1  |  2024-11-29: 1  |  2024-10-10: 1  |  2024-04-04: 1
2024-07-03: 1  |  2024-06-01: 1  |  2024-09-04: 1  |  2024-10-12: 1  |  2024-08-12: 1
2024-03-30: 1  |  2024-12-11: 1  |  2024-02-16: 1  |  2024-02-29: 1  |  2024-01-28: 1
2024-10-08: 1  |  2024-05-04: 1  |  2024-06-13: 1  |  2024-08-30: 1  |  2024-03-05: 1
2024-01-08: 1  |  2024-12-20: 1  |  2024-10-04: 1  |  2024-11-20: 1  |  2024-02-10: 1
2024-11-23: 1  |  2024-07-14: 1  |  2024-10-16: 1  |  2024-11-06: 1  |  2024-11-17: 1
2024-03-25: 1  |  2024-04-23: 1  |  2024-01-24: 1  |  2024-08-20: 1  |  2024-09-07: 1
2024-04-07: 1  |  2024-06-19: 1  |  2024-04-20: 1  |  2024-10-28: 1  |  2024-08-31: 1
2024-06-03: 1  |  2024-09-08: 1  |  2024-11-15: 1  |  2024-06-09: 1  |  2024-08-09: 1
2024-12-09: 1  |  2024-07-07: 1  |  2024-01-14: 1

[ CLIENTE ]
Cliente_024: 8  |  Cliente_009: 8  |  Cliente_029: 7  |  Cliente_019: 7  |  Cliente_020: 7
Cliente_015: 7  |  Cliente_022: 7  |  Cliente_014: 7  |  Cliente_008: 6  |  Cliente_026: 6
Cliente_001: 6  |  Cliente_005: 6  |  Cliente_013: 6  |  Cliente_018: 6  |  Cliente_017: 5
Cliente_016: 5  |  Cliente_003: 5  |  Cliente_004: 5  |  Cliente_025: 5  |  Cliente_030: 4
Cliente_023: 4  |  Cliente_027: 3  |  Cliente_028: 3  |  Cliente_002: 3  |  Cliente_007: 3
Cliente_012: 3  |  Cliente_011: 2  |  Cliente_006: 2  |  Cliente_021: 2  |  Cliente_010: 2

[ PRODUTO ]
Notebook: 27  |  Smartphone: 25  |  Tablet: 25  |  Mouse: 24  |  Monitor: 24
Teclado: 22  |  Tablet : 1  |  Smartphone : 1  |   Smartphone : 1

[ CATEGORIA ]
Celulares: 53  |  Computadores: 51  |  Periféricos: 46

[ REGIAO ]
Sudeste: 42  |  Norte: 35  |  Centro-Oeste: 27  |  Sul: 23  |  Nordeste: 23

[ QUANTIDADE ]
8.0: 21  |  4.0: 20  |  2.0: 19  |  5.0: 17  |  9.0: 12
6.0: 12  |  7.0: 12  |  3.0: 12  |  10.0: 10  |  1.0: 9

[ PRECO_UNITARIO ]
3500.0: 27  |  2200.0: 27  |  1800.0: 25  |  120.0: 24  |  1200.0: 23
250.0: 21